import { Injectable, Logger } from '@nestjs/common';
import { teams } from '@iknoball/database';
import { eq } from 'drizzle-orm';
import { DatabaseService } from './database.service';

const L = 'https://cdn.nba.com/logos/nba';

interface NBATeamSeed {
  externalId: number;
  abbreviation: string;
  teamName: string;
  fullName: string;
  city: string;
  conference: 'East' | 'West';
  division: 'Atlantic' | 'Central' | 'Southeast' | 'Northwest' | 'Pacific' | 'Southwest';
  logoUrl: string;
  arena: string;
  headCoach: string;
  primaryColor: string;
}

const nbaTeams: NBATeamSeed[] = [
  // ── Western Conference ──────────────────────────────────────
  // Northwest
  {
    externalId: 1610612743,
    abbreviation: 'DEN',
    teamName: 'Nuggets',
    fullName: 'Denver Nuggets',
    city: 'Denver',
    conference: 'West',
    division: 'Northwest',
    logoUrl: `${L}/1610612743/global/L/logo.svg`,
    arena: 'Ball Arena',
    headCoach: 'David Adelman',
    primaryColor: '#0E2240',
  },
  {
    externalId: 1610612750,
    abbreviation: 'MIN',
    teamName: 'Timberwolves',
    fullName: 'Minnesota Timberwolves',
    city: 'Minneapolis',
    conference: 'West',
    division: 'Northwest',
    logoUrl: `${L}/1610612750/global/L/logo.svg`,
    arena: 'Target Center',
    headCoach: 'Chris Finch',
    primaryColor: '#0C2340',
  },
  {
    externalId: 1610612760,
    abbreviation: 'OKC',
    teamName: 'Thunder',
    fullName: 'Oklahoma City Thunder',
    city: 'Oklahoma City',
    conference: 'West',
    division: 'Northwest',
    logoUrl: `${L}/1610612760/global/L/logo.svg`,
    arena: 'Paycom Center',
    headCoach: 'Mark Daigneault',
    primaryColor: '#007AC1',
  },
  {
    externalId: 1610612757,
    abbreviation: 'POR',
    teamName: 'Trail Blazers',
    fullName: 'Portland Trail Blazers',
    city: 'Portland',
    conference: 'West',
    division: 'Northwest',
    logoUrl: `${L}/1610612757/global/L/logo.svg`,
    arena: 'Moda Center',
    headCoach: 'Chauncey Billups',
    primaryColor: '#E03A3E',
  },
  {
    externalId: 1610612762,
    abbreviation: 'UTA',
    teamName: 'Jazz',
    fullName: 'Utah Jazz',
    city: 'Salt Lake City',
    conference: 'West',
    division: 'Northwest',
    logoUrl: `${L}/1610612762/global/L/logo.svg`,
    arena: 'Delta Center',
    headCoach: 'Will Hardy',
    primaryColor: '#002B5C',
  },
  // Pacific
  {
    externalId: 1610612744,
    abbreviation: 'GSW',
    teamName: 'Warriors',
    fullName: 'Golden State Warriors',
    city: 'San Francisco',
    conference: 'West',
    division: 'Pacific',
    logoUrl: `${L}/1610612744/global/L/logo.svg`,
    arena: 'Chase Center',
    headCoach: 'Steve Kerr',
    primaryColor: '#1D428A',
  },
  {
    externalId: 1610612746,
    abbreviation: 'LAC',
    teamName: 'Clippers',
    fullName: 'LA Clippers',
    city: 'Los Angeles',
    conference: 'West',
    division: 'Pacific',
    logoUrl: `${L}/1610612746/global/L/logo.svg`,
    arena: 'Intuit Dome',
    headCoach: 'Tyronn Lue',
    primaryColor: '#C8102E',
  },
  {
    externalId: 1610612747,
    abbreviation: 'LAL',
    teamName: 'Lakers',
    fullName: 'Los Angeles Lakers',
    city: 'Los Angeles',
    conference: 'West',
    division: 'Pacific',
    logoUrl: `${L}/1610612747/global/L/logo.svg`,
    arena: 'Crypto.com Arena',
    headCoach: 'JJ Redick',
    primaryColor: '#552583',
  },
  {
    externalId: 1610612756,
    abbreviation: 'PHX',
    teamName: 'Suns',
    fullName: 'Phoenix Suns',
    city: 'Phoenix',
    conference: 'West',
    division: 'Pacific',
    logoUrl: `${L}/1610612756/global/L/logo.svg`,
    arena: 'Footprint Center',
    headCoach: 'Mike Budenholzer',
    primaryColor: '#1D1160',
  },
  {
    externalId: 1610612758,
    abbreviation: 'SAC',
    teamName: 'Kings',
    fullName: 'Sacramento Kings',
    city: 'Sacramento',
    conference: 'West',
    division: 'Pacific',
    logoUrl: `${L}/1610612758/global/L/logo.svg`,
    arena: 'Golden 1 Center',
    headCoach: 'Doug Christie',
    primaryColor: '#5A2D81',
  },
  // Southwest
  {
    externalId: 1610612742,
    abbreviation: 'DAL',
    teamName: 'Mavericks',
    fullName: 'Dallas Mavericks',
    city: 'Dallas',
    conference: 'West',
    division: 'Southwest',
    logoUrl: `${L}/1610612742/global/L/logo.svg`,
    arena: 'American Airlines Center',
    headCoach: 'Jason Kidd',
    primaryColor: '#00538C',
  },
  {
    externalId: 1610612745,
    abbreviation: 'HOU',
    teamName: 'Rockets',
    fullName: 'Houston Rockets',
    city: 'Houston',
    conference: 'West',
    division: 'Southwest',
    logoUrl: `${L}/1610612745/global/L/logo.svg`,
    arena: 'Toyota Center',
    headCoach: 'Ime Udoka',
    primaryColor: '#CE1141',
  },
  {
    externalId: 1610612763,
    abbreviation: 'MEM',
    teamName: 'Grizzlies',
    fullName: 'Memphis Grizzlies',
    city: 'Memphis',
    conference: 'West',
    division: 'Southwest',
    logoUrl: `${L}/1610612763/global/L/logo.svg`,
    arena: 'FedExForum',
    headCoach: 'Taylor Jenkins',
    primaryColor: '#5D76A9',
  },
  {
    externalId: 1610612740,
    abbreviation: 'NOP',
    teamName: 'Pelicans',
    fullName: 'New Orleans Pelicans',
    city: 'New Orleans',
    conference: 'West',
    division: 'Southwest',
    logoUrl: `${L}/1610612740/global/L/logo.svg`,
    arena: 'Smoothie King Center',
    headCoach: 'Willie Green',
    primaryColor: '#0C2340',
  },
  {
    externalId: 1610612759,
    abbreviation: 'SAS',
    teamName: 'Spurs',
    fullName: 'San Antonio Spurs',
    city: 'San Antonio',
    conference: 'West',
    division: 'Southwest',
    logoUrl: `${L}/1610612759/global/L/logo.svg`,
    arena: 'Frost Bank Center',
    headCoach: 'Mitch Johnson',
    primaryColor: '#C4CED4',
  },

  // ── Eastern Conference ──────────────────────────────────────
  // Atlantic
  {
    externalId: 1610612738,
    abbreviation: 'BOS',
    teamName: 'Celtics',
    fullName: 'Boston Celtics',
    city: 'Boston',
    conference: 'East',
    division: 'Atlantic',
    logoUrl: `${L}/1610612738/global/L/logo.svg`,
    arena: 'TD Garden',
    headCoach: 'Joe Mazzulla',
    primaryColor: '#007A33',
  },
  {
    externalId: 1610612751,
    abbreviation: 'BRK',
    teamName: 'Nets',
    fullName: 'Brooklyn Nets',
    city: 'Brooklyn',
    conference: 'East',
    division: 'Atlantic',
    logoUrl: `${L}/1610612751/global/L/logo.svg`,
    arena: 'Barclays Center',
    headCoach: 'Jordi Fernández',
    primaryColor: '#000000',
  },
  {
    externalId: 1610612752,
    abbreviation: 'NYK',
    teamName: 'Knicks',
    fullName: 'New York Knicks',
    city: 'New York',
    conference: 'East',
    division: 'Atlantic',
    logoUrl: `${L}/1610612752/global/L/logo.svg`,
    arena: 'Madison Square Garden',
    headCoach: 'Tom Thibodeau',
    primaryColor: '#006BB6',
  },
  {
    externalId: 1610612755,
    abbreviation: 'PHI',
    teamName: '76ers',
    fullName: 'Philadelphia 76ers',
    city: 'Philadelphia',
    conference: 'East',
    division: 'Atlantic',
    logoUrl: `${L}/1610612755/global/L/logo.svg`,
    arena: 'Wells Fargo Center',
    headCoach: 'Nick Nurse',
    primaryColor: '#006BB6',
  },
  {
    externalId: 1610612761,
    abbreviation: 'TOR',
    teamName: 'Raptors',
    fullName: 'Toronto Raptors',
    city: 'Toronto',
    conference: 'East',
    division: 'Atlantic',
    logoUrl: `${L}/1610612761/global/L/logo.svg`,
    arena: 'Scotiabank Arena',
    headCoach: 'Darko Rajaković',
    primaryColor: '#CE1141',
  },
  // Central
  {
    externalId: 1610612741,
    abbreviation: 'CHI',
    teamName: 'Bulls',
    fullName: 'Chicago Bulls',
    city: 'Chicago',
    conference: 'East',
    division: 'Central',
    logoUrl: `${L}/1610612741/global/L/logo.svg`,
    arena: 'United Center',
    headCoach: 'Billy Donovan',
    primaryColor: '#CE1141',
  },
  {
    externalId: 1610612739,
    abbreviation: 'CLE',
    teamName: 'Cavaliers',
    fullName: 'Cleveland Cavaliers',
    city: 'Cleveland',
    conference: 'East',
    division: 'Central',
    logoUrl: `${L}/1610612739/global/L/logo.svg`,
    arena: 'Rocket Mortgage FieldHouse',
    headCoach: 'Kenny Atkinson',
    primaryColor: '#860038',
  },
  {
    externalId: 1610612765,
    abbreviation: 'DET',
    teamName: 'Pistons',
    fullName: 'Detroit Pistons',
    city: 'Detroit',
    conference: 'East',
    division: 'Central',
    logoUrl: `${L}/1610612765/global/L/logo.svg`,
    arena: 'Little Caesars Arena',
    headCoach: 'J.B. Bickerstaff',
    primaryColor: '#C8102E',
  },
  {
    externalId: 1610612754,
    abbreviation: 'IND',
    teamName: 'Pacers',
    fullName: 'Indiana Pacers',
    city: 'Indianapolis',
    conference: 'East',
    division: 'Central',
    logoUrl: `${L}/1610612754/global/L/logo.svg`,
    arena: 'Gainbridge Fieldhouse',
    headCoach: 'Rick Carlisle',
    primaryColor: '#002D62',
  },
  {
    externalId: 1610612749,
    abbreviation: 'MIL',
    teamName: 'Bucks',
    fullName: 'Milwaukee Bucks',
    city: 'Milwaukee',
    conference: 'East',
    division: 'Central',
    logoUrl: `${L}/1610612749/global/L/logo.svg`,
    arena: 'Fiserv Forum',
    headCoach: 'Doc Rivers',
    primaryColor: '#00471B',
  },
  // Southeast
  {
    externalId: 1610612737,
    abbreviation: 'ATL',
    teamName: 'Hawks',
    fullName: 'Atlanta Hawks',
    city: 'Atlanta',
    conference: 'East',
    division: 'Southeast',
    logoUrl: `${L}/1610612737/global/L/logo.svg`,
    arena: 'State Farm Arena',
    headCoach: 'Quin Snyder',
    primaryColor: '#E03A3E',
  },
  {
    externalId: 1610612766,
    abbreviation: 'CHO',
    teamName: 'Hornets',
    fullName: 'Charlotte Hornets',
    city: 'Charlotte',
    conference: 'East',
    division: 'Southeast',
    logoUrl: `${L}/1610612766/global/L/logo.svg`,
    arena: 'Spectrum Center',
    headCoach: 'Charles Lee',
    primaryColor: '#1D1160',
  },
  {
    externalId: 1610612748,
    abbreviation: 'MIA',
    teamName: 'Heat',
    fullName: 'Miami Heat',
    city: 'Miami',
    conference: 'East',
    division: 'Southeast',
    logoUrl: `${L}/1610612748/global/L/logo.svg`,
    arena: 'Kaseya Center',
    headCoach: 'Erik Spoelstra',
    primaryColor: '#98002E',
  },
  {
    externalId: 1610612753,
    abbreviation: 'ORL',
    teamName: 'Magic',
    fullName: 'Orlando Magic',
    city: 'Orlando',
    conference: 'East',
    division: 'Southeast',
    logoUrl: `${L}/1610612753/global/L/logo.svg`,
    arena: 'Kia Center',
    headCoach: 'Jamahl Mosley',
    primaryColor: '#0077C0',
  },
  {
    externalId: 1610612764,
    abbreviation: 'WAS',
    teamName: 'Wizards',
    fullName: 'Washington Wizards',
    city: 'Washington, D.C.',
    conference: 'East',
    division: 'Southeast',
    logoUrl: `${L}/1610612764/global/L/logo.svg`,
    arena: 'Capital One Arena',
    headCoach: 'Brian Keefe',
    primaryColor: '#002B5C',
  },
];

@Injectable()
export class TeamSeedService {
  private readonly logger = new Logger(TeamSeedService.name);

  constructor(private readonly database: DatabaseService) {}

  async seed(): Promise<void> {
    this.logger.log(`Seeding ${nbaTeams.length} NBA teams...`);

    let inserted = 0;
    for (const team of nbaTeams) {
      const now = new Date();
      await this.database.db
        .insert(teams)
        .values({
          externalId: String(team.externalId),
          name: team.teamName,
          fullName: team.fullName,
          abbreviation: team.abbreviation,
          city: team.city,
          conference: team.conference,
          division: team.division,
          logoUrl: team.logoUrl,
          arena: team.arena,
          headCoach: team.headCoach,
          primaryColor: team.primaryColor,
          createdAt: now,
          updatedAt: now,
        })
        .onConflictDoUpdate({
          target: teams.externalId,
          set: {
            name: team.teamName,
            fullName: team.fullName,
            abbreviation: team.abbreviation,
            city: team.city,
            conference: team.conference,
            division: team.division,
            logoUrl: team.logoUrl,
            arena: team.arena,
            headCoach: team.headCoach,
            primaryColor: team.primaryColor,
            updatedAt: now,
          },
        });

      inserted++;
      if (inserted % 10 === 0) {
        this.logger.log(`Progress: ${inserted}/${nbaTeams.length} teams seeded`);
      }
    }

    this.logger.log(`Done — ${inserted} teams seeded`);
  }
}
