version: "3.9"

services:
  api:
    image: ghcr.io/seto-techs/iknoball-be:${IMAGE_TAG}
    container_name: iknoball-api
    env_file:
      - .env
    ports:
      - "127.0.0.1:20003:3000" # host 20002 -> container 3000
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app_net
      - redis_log_net

  web:
    image: ghcr.io/seto-techs/iknoball-fe:${IMAGE_TAG}
    container_name: iknoball-web
    env_file:
      - .env
    ports:
      - "127.0.0.1:21009:3000"
    restart: unless-stopped
    networks:
      - app_net

  redis:
    image: redis:7-alpine
    container_name: iknoball-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - "6103:6379" # untuk RedisInsight
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - app_net

volumes:
  redis-data:

networks:
  app_net:
    name: iknoball_app_net
    driver: bridge

  redis_log_net:
    external: true
    name: redis_redis-log-network
